server.port=8081

# Production Supabase PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.rofhcjedmviwzysipmav}
spring.datasource.password=${DB_PASSWORD:SreeSri@2007}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configurations
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gemini LLM configurations
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Gmail API Configuration for OAuth
gmail.client.id=${GMAIL_CLIENT_ID:}
gmail.client.secret=${GMAIL_CLIENT_SECRET:}

# Razorpay API Credentials
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_TD5IJ7If16ZHbr}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:B2KV5qc0buHLMtWqlG9uj2oJ}
gmail.refresh.token=${GMAIL_REFRESH_TOKEN:}
gmail.auth.email=${GMAIL_AUTH_EMAIL:hello@reevibes.com}
gmail.otp.from=${GMAIL_OTP_FROM:no-reply@reevibes.com}
gmail.welcome.from=${GMAIL_WELCOME_FROM:hello@reevibes.com}
gmail.from.name=${GMAIL_FROM_NAME:ReeVibes}
gmail.reply.to=${GMAIL_REPLY_TO:hello@reevibes.com}

