/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as FashionBattleIndexRouteImport } from './routes/FashionBattle.index'
import { Route as ApiSponsorsRouteImport } from './routes/api.sponsors'
import { Route as ApiFlagsRouteImport } from './routes/api.flags'
import { Route as ApiCountriesLogosRouteImport } from './routes/api.countries-logos'
import { Route as ApiAngelsRouteImport } from './routes/api.angels'
import { Route as AdminVoteControlRouteImport } from './routes/admin.vote-control'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTop16RouteImport } from './routes/admin.top-16'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPhotographersRouteImport } from './routes/admin.photographers'
import { Route as AdminOpenContestRouteImport } from './routes/admin.open-contest'
import { Route as AdminLiveContestRouteImport } from './routes/admin.live-contest'
import { Route as AdminContestantsRouteImport } from './routes/admin.contestants'
import { Route as AdminAbuseReportsRouteImport } from './routes/admin.abuse-reports'
import { Route as ShopWishlistRouteImport } from './routes/_shop.wishlist'
import { Route as ShopShopRouteImport } from './routes/_shop.shop'
import { Route as ShopSearchRouteImport } from './routes/_shop.search'
import { Route as ShopRegisterRouteImport } from './routes/_shop.register'
import { Route as ShopOrdersRouteImport } from './routes/_shop.orders'
import { Route as ShopLoginRouteImport } from './routes/_shop.login'
import { Route as ShopForgotPasswordRouteImport } from './routes/_shop.forgot-password'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCategoriesRouteImport } from './routes/_shop.categories'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as FashionBattleRegisterRouteImport } from './routes/FashionBattle.register'
import { Route as FashionBattleLoginRouteImport } from './routes/FashionBattle.login'
import { Route as FashionBattleLiveContestRouteImport } from './routes/FashionBattle.live-contest'
import { Route as FashionBattleHouseOfFashionRouteImport } from './routes/FashionBattle.house-of-fashion'
import { Route as FashionBattleCartRouteImport } from './routes/FashionBattle.cart'
import { Route as FashionBattleBestPhotographyRouteImport } from './routes/FashionBattle.best-photography'
import { Route as FashionBattleApplyRouteImport } from './routes/FashionBattle.apply'
import { Route as FashionBattleAngelsRouteImport } from './routes/FashionBattle.angels'
import { Route as FashionBattleAccountRouteImport } from './routes/FashionBattle.account'
import { Route as FashionBattleAboutRouteImport } from './routes/FashionBattle.about'
import { Route as FashionBattleApplyIndexRouteImport } from './routes/FashionBattle.apply.index'
import { Route as FashionBattleAccountIndexRouteImport } from './routes/FashionBattle.account.index'
import { Route as ShopProductProductIdRouteImport } from './routes/_shop.product.$productId'
import { Route as ShopCategoryCategorySlugRouteImport } from './routes/_shop.category.$categorySlug'
import { Route as ShopBrandBrandSlugRouteImport } from './routes/_shop.brand.$brandSlug'
import { Route as FashionBattlePhotographyPhotoIdRouteImport } from './routes/FashionBattle.photography.$photoId'
import { Route as FashionBattleLiveContestContestIdRouteImport } from './routes/FashionBattle.live-contest.$contestId'
import { Route as FashionBattleHouseOfFashionProductIdRouteImport } from './routes/FashionBattle.house-of-fashion.$productId'
import { Route as FashionBattleContestantsSlugRouteImport } from './routes/FashionBattle.contestants.$slug'
import { Route as FashionBattleContestantContestantIdRouteImport } from './routes/FashionBattle.contestant.$contestantId'
import { Route as FashionBattleApplyContestIdRouteImport } from './routes/FashionBattle.apply.$contestId'
import { Route as FashionBattleAngelsSlugRouteImport } from './routes/FashionBattle.angels.$slug'
import { Route as FashionBattleAccountRoleRatingsRouteImport } from './routes/FashionBattle.account.role-ratings'
import { Route as FashionBattleAccountRoleJudgementsRouteImport } from './routes/FashionBattle.account.role-judgements'
import { Route as FashionBattleAccountRoleCastingRouteImport } from './routes/FashionBattle.account.role-casting'
import { Route as FashionBattleAccountRoleApplicationsRouteImport } from './routes/FashionBattle.account.role-applications'
import { Route as FashionBattleAccountProfileRouteImport } from './routes/FashionBattle.account.profile'
import { Route as FashionBattleAccountNotificationsRouteImport } from './routes/FashionBattle.account.notifications'
import { Route as FashionBattleAccountApplicationsRouteImport } from './routes/FashionBattle.account.applications'
import { Route as FashionBattleLiveContestCountryIdStageRouteImport } from './routes/FashionBattle.live-contest.$countryId.$stage'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const FashionBattleIndexRoute = FashionBattleIndexRouteImport.update({
  id: '/FashionBattle/',
  path: '/FashionBattle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorsRoute = ApiSponsorsRouteImport.update({
  id: '/api/sponsors',
  path: '/api/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagsRoute = ApiFlagsRouteImport.update({
  id: '/api/flags',
  path: '/api/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesLogosRoute = ApiCountriesLogosRouteImport.update({
  id: '/api/countries-logos',
  path: '/api/countries-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAngelsRoute = ApiAngelsRouteImport.update({
  id: '/api/angels',
  path: '/api/angels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoteControlRoute = AdminVoteControlRouteImport.update({
  id: '/admin/vote-control',
  path: '/admin/vote-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTop16Route = AdminTop16RouteImport.update({
  id: '/admin/top-16',
  path: '/admin/top-16',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotographersRoute = AdminPhotographersRouteImport.update({
  id: '/admin/photographers',
  path: '/admin/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpenContestRoute = AdminOpenContestRouteImport.update({
  id: '/admin/open-contest',
  path: '/admin/open-contest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveContestRoute = AdminLiveContestRouteImport.update({
  id: '/admin/live-contest',
  path: '/admin/live-contest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestantsRoute = AdminContestantsRouteImport.update({
  id: '/admin/contestants',
  path: '/admin/contestants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbuseReportsRoute = AdminAbuseReportsRouteImport.update({
  id: '/admin/abuse-reports',
  path: '/admin/abuse-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopShopRoute = ShopShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRegisterRoute = ShopRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopForgotPasswordRoute = ShopForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoriesRoute = ShopCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const FashionBattleRegisterRoute = FashionBattleRegisterRouteImport.update({
  id: '/FashionBattle/register',
  path: '/FashionBattle/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleLoginRoute = FashionBattleLoginRouteImport.update({
  id: '/FashionBattle/login',
  path: '/FashionBattle/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleLiveContestRoute =
  FashionBattleLiveContestRouteImport.update({
    id: '/FashionBattle/live-contest',
    path: '/FashionBattle/live-contest',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleHouseOfFashionRoute =
  FashionBattleHouseOfFashionRouteImport.update({
    id: '/FashionBattle/house-of-fashion',
    path: '/FashionBattle/house-of-fashion',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleCartRoute = FashionBattleCartRouteImport.update({
  id: '/FashionBattle/cart',
  path: '/FashionBattle/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleBestPhotographyRoute =
  FashionBattleBestPhotographyRouteImport.update({
    id: '/FashionBattle/best-photography',
    path: '/FashionBattle/best-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleApplyRoute = FashionBattleApplyRouteImport.update({
  id: '/FashionBattle/apply',
  path: '/FashionBattle/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleAngelsRoute = FashionBattleAngelsRouteImport.update({
  id: '/FashionBattle/angels',
  path: '/FashionBattle/angels',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleAccountRoute = FashionBattleAccountRouteImport.update({
  id: '/FashionBattle/account',
  path: '/FashionBattle/account',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleAboutRoute = FashionBattleAboutRouteImport.update({
  id: '/FashionBattle/about',
  path: '/FashionBattle/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionBattleApplyIndexRoute = FashionBattleApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FashionBattleApplyRoute,
} as any)
const FashionBattleAccountIndexRoute =
  FashionBattleAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const ShopProductProductIdRoute = ShopProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoryCategorySlugRoute =
  ShopCategoryCategorySlugRouteImport.update({
    id: '/category/$categorySlug',
    path: '/category/$categorySlug',
    getParentRoute: () => ShopRoute,
  } as any)
const ShopBrandBrandSlugRoute = ShopBrandBrandSlugRouteImport.update({
  id: '/brand/$brandSlug',
  path: '/brand/$brandSlug',
  getParentRoute: () => ShopRoute,
} as any)
const FashionBattlePhotographyPhotoIdRoute =
  FashionBattlePhotographyPhotoIdRouteImport.update({
    id: '/FashionBattle/photography/$photoId',
    path: '/FashionBattle/photography/$photoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleLiveContestContestIdRoute =
  FashionBattleLiveContestContestIdRouteImport.update({
    id: '/$contestId',
    path: '/$contestId',
    getParentRoute: () => FashionBattleLiveContestRoute,
  } as any)
const FashionBattleHouseOfFashionProductIdRoute =
  FashionBattleHouseOfFashionProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => FashionBattleHouseOfFashionRoute,
  } as any)
const FashionBattleContestantsSlugRoute =
  FashionBattleContestantsSlugRouteImport.update({
    id: '/FashionBattle/contestants/$slug',
    path: '/FashionBattle/contestants/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleContestantContestantIdRoute =
  FashionBattleContestantContestantIdRouteImport.update({
    id: '/FashionBattle/contestant/$contestantId',
    path: '/FashionBattle/contestant/$contestantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FashionBattleApplyContestIdRoute =
  FashionBattleApplyContestIdRouteImport.update({
    id: '/$contestId',
    path: '/$contestId',
    getParentRoute: () => FashionBattleApplyRoute,
  } as any)
const FashionBattleAngelsSlugRoute = FashionBattleAngelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FashionBattleAngelsRoute,
} as any)
const FashionBattleAccountRoleRatingsRoute =
  FashionBattleAccountRoleRatingsRouteImport.update({
    id: '/role-ratings',
    path: '/role-ratings',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountRoleJudgementsRoute =
  FashionBattleAccountRoleJudgementsRouteImport.update({
    id: '/role-judgements',
    path: '/role-judgements',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountRoleCastingRoute =
  FashionBattleAccountRoleCastingRouteImport.update({
    id: '/role-casting',
    path: '/role-casting',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountRoleApplicationsRoute =
  FashionBattleAccountRoleApplicationsRouteImport.update({
    id: '/role-applications',
    path: '/role-applications',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountProfileRoute =
  FashionBattleAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountNotificationsRoute =
  FashionBattleAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleAccountApplicationsRoute =
  FashionBattleAccountApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => FashionBattleAccountRoute,
  } as any)
const FashionBattleLiveContestCountryIdStageRoute =
  FashionBattleLiveContestCountryIdStageRouteImport.update({
    id: '/$countryId/$stage',
    path: '/$countryId/$stage',
    getParentRoute: () => FashionBattleLiveContestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/FashionBattle/about': typeof FashionBattleAboutRoute
  '/FashionBattle/account': typeof FashionBattleAccountRouteWithChildren
  '/FashionBattle/angels': typeof FashionBattleAngelsRouteWithChildren
  '/FashionBattle/apply': typeof FashionBattleApplyRouteWithChildren
  '/FashionBattle/best-photography': typeof FashionBattleBestPhotographyRoute
  '/FashionBattle/cart': typeof FashionBattleCartRoute
  '/FashionBattle/house-of-fashion': typeof FashionBattleHouseOfFashionRouteWithChildren
  '/FashionBattle/live-contest': typeof FashionBattleLiveContestRouteWithChildren
  '/FashionBattle/login': typeof FashionBattleLoginRoute
  '/FashionBattle/register': typeof FashionBattleRegisterRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/categories': typeof ShopCategoriesRoute
  '/checkout': typeof ShopCheckoutRoute
  '/forgot-password': typeof ShopForgotPasswordRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/register': typeof ShopRegisterRoute
  '/search': typeof ShopSearchRoute
  '/shop': typeof ShopShopRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/FashionBattle/': typeof FashionBattleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/FashionBattle/account/applications': typeof FashionBattleAccountApplicationsRoute
  '/FashionBattle/account/notifications': typeof FashionBattleAccountNotificationsRoute
  '/FashionBattle/account/profile': typeof FashionBattleAccountProfileRoute
  '/FashionBattle/account/role-applications': typeof FashionBattleAccountRoleApplicationsRoute
  '/FashionBattle/account/role-casting': typeof FashionBattleAccountRoleCastingRoute
  '/FashionBattle/account/role-judgements': typeof FashionBattleAccountRoleJudgementsRoute
  '/FashionBattle/account/role-ratings': typeof FashionBattleAccountRoleRatingsRoute
  '/FashionBattle/angels/$slug': typeof FashionBattleAngelsSlugRoute
  '/FashionBattle/apply/$contestId': typeof FashionBattleApplyContestIdRoute
  '/FashionBattle/contestant/$contestantId': typeof FashionBattleContestantContestantIdRoute
  '/FashionBattle/contestants/$slug': typeof FashionBattleContestantsSlugRoute
  '/FashionBattle/house-of-fashion/$productId': typeof FashionBattleHouseOfFashionProductIdRoute
  '/FashionBattle/live-contest/$contestId': typeof FashionBattleLiveContestContestIdRoute
  '/FashionBattle/photography/$photoId': typeof FashionBattlePhotographyPhotoIdRoute
  '/brand/$brandSlug': typeof ShopBrandBrandSlugRoute
  '/category/$categorySlug': typeof ShopCategoryCategorySlugRoute
  '/product/$productId': typeof ShopProductProductIdRoute
  '/FashionBattle/account/': typeof FashionBattleAccountIndexRoute
  '/FashionBattle/apply/': typeof FashionBattleApplyIndexRoute
  '/FashionBattle/live-contest/$countryId/$stage': typeof FashionBattleLiveContestCountryIdStageRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/FashionBattle/about': typeof FashionBattleAboutRoute
  '/FashionBattle/angels': typeof FashionBattleAngelsRouteWithChildren
  '/FashionBattle/best-photography': typeof FashionBattleBestPhotographyRoute
  '/FashionBattle/cart': typeof FashionBattleCartRoute
  '/FashionBattle/house-of-fashion': typeof FashionBattleHouseOfFashionRouteWithChildren
  '/FashionBattle/live-contest': typeof FashionBattleLiveContestRouteWithChildren
  '/FashionBattle/login': typeof FashionBattleLoginRoute
  '/FashionBattle/register': typeof FashionBattleRegisterRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/categories': typeof ShopCategoriesRoute
  '/checkout': typeof ShopCheckoutRoute
  '/forgot-password': typeof ShopForgotPasswordRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/register': typeof ShopRegisterRoute
  '/search': typeof ShopSearchRoute
  '/shop': typeof ShopShopRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/FashionBattle': typeof FashionBattleIndexRoute
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminIndexRoute
  '/FashionBattle/account/applications': typeof FashionBattleAccountApplicationsRoute
  '/FashionBattle/account/notifications': typeof FashionBattleAccountNotificationsRoute
  '/FashionBattle/account/profile': typeof FashionBattleAccountProfileRoute
  '/FashionBattle/account/role-applications': typeof FashionBattleAccountRoleApplicationsRoute
  '/FashionBattle/account/role-casting': typeof FashionBattleAccountRoleCastingRoute
  '/FashionBattle/account/role-judgements': typeof FashionBattleAccountRoleJudgementsRoute
  '/FashionBattle/account/role-ratings': typeof FashionBattleAccountRoleRatingsRoute
  '/FashionBattle/angels/$slug': typeof FashionBattleAngelsSlugRoute
  '/FashionBattle/apply/$contestId': typeof FashionBattleApplyContestIdRoute
  '/FashionBattle/contestant/$contestantId': typeof FashionBattleContestantContestantIdRoute
  '/FashionBattle/contestants/$slug': typeof FashionBattleContestantsSlugRoute
  '/FashionBattle/house-of-fashion/$productId': typeof FashionBattleHouseOfFashionProductIdRoute
  '/FashionBattle/live-contest/$contestId': typeof FashionBattleLiveContestContestIdRoute
  '/FashionBattle/photography/$photoId': typeof FashionBattlePhotographyPhotoIdRoute
  '/brand/$brandSlug': typeof ShopBrandBrandSlugRoute
  '/category/$categorySlug': typeof ShopCategoryCategorySlugRoute
  '/product/$productId': typeof ShopProductProductIdRoute
  '/FashionBattle/account': typeof FashionBattleAccountIndexRoute
  '/FashionBattle/apply': typeof FashionBattleApplyIndexRoute
  '/FashionBattle/live-contest/$countryId/$stage': typeof FashionBattleLiveContestCountryIdStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/FashionBattle/about': typeof FashionBattleAboutRoute
  '/FashionBattle/account': typeof FashionBattleAccountRouteWithChildren
  '/FashionBattle/angels': typeof FashionBattleAngelsRouteWithChildren
  '/FashionBattle/apply': typeof FashionBattleApplyRouteWithChildren
  '/FashionBattle/best-photography': typeof FashionBattleBestPhotographyRoute
  '/FashionBattle/cart': typeof FashionBattleCartRoute
  '/FashionBattle/house-of-fashion': typeof FashionBattleHouseOfFashionRouteWithChildren
  '/FashionBattle/live-contest': typeof FashionBattleLiveContestRouteWithChildren
  '/FashionBattle/login': typeof FashionBattleLoginRoute
  '/FashionBattle/register': typeof FashionBattleRegisterRoute
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/categories': typeof ShopCategoriesRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/forgot-password': typeof ShopForgotPasswordRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/register': typeof ShopRegisterRoute
  '/_shop/search': typeof ShopSearchRoute
  '/_shop/shop': typeof ShopShopRoute
  '/_shop/wishlist': typeof ShopWishlistRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/FashionBattle/': typeof FashionBattleIndexRoute
  '/_shop/': typeof ShopIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/FashionBattle/account/applications': typeof FashionBattleAccountApplicationsRoute
  '/FashionBattle/account/notifications': typeof FashionBattleAccountNotificationsRoute
  '/FashionBattle/account/profile': typeof FashionBattleAccountProfileRoute
  '/FashionBattle/account/role-applications': typeof FashionBattleAccountRoleApplicationsRoute
  '/FashionBattle/account/role-casting': typeof FashionBattleAccountRoleCastingRoute
  '/FashionBattle/account/role-judgements': typeof FashionBattleAccountRoleJudgementsRoute
  '/FashionBattle/account/role-ratings': typeof FashionBattleAccountRoleRatingsRoute
  '/FashionBattle/angels/$slug': typeof FashionBattleAngelsSlugRoute
  '/FashionBattle/apply/$contestId': typeof FashionBattleApplyContestIdRoute
  '/FashionBattle/contestant/$contestantId': typeof FashionBattleContestantContestantIdRoute
  '/FashionBattle/contestants/$slug': typeof FashionBattleContestantsSlugRoute
  '/FashionBattle/house-of-fashion/$productId': typeof FashionBattleHouseOfFashionProductIdRoute
  '/FashionBattle/live-contest/$contestId': typeof FashionBattleLiveContestContestIdRoute
  '/FashionBattle/photography/$photoId': typeof FashionBattlePhotographyPhotoIdRoute
  '/_shop/brand/$brandSlug': typeof ShopBrandBrandSlugRoute
  '/_shop/category/$categorySlug': typeof ShopCategoryCategorySlugRoute
  '/_shop/product/$productId': typeof ShopProductProductIdRoute
  '/FashionBattle/account/': typeof FashionBattleAccountIndexRoute
  '/FashionBattle/apply/': typeof FashionBattleApplyIndexRoute
  '/FashionBattle/live-contest/$countryId/$stage': typeof FashionBattleLiveContestCountryIdStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/FashionBattle/about'
    | '/FashionBattle/account'
    | '/FashionBattle/angels'
    | '/FashionBattle/apply'
    | '/FashionBattle/best-photography'
    | '/FashionBattle/cart'
    | '/FashionBattle/house-of-fashion'
    | '/FashionBattle/live-contest'
    | '/FashionBattle/login'
    | '/FashionBattle/register'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/shop'
    | '/wishlist'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/FashionBattle/'
    | '/admin/'
    | '/FashionBattle/account/applications'
    | '/FashionBattle/account/notifications'
    | '/FashionBattle/account/profile'
    | '/FashionBattle/account/role-applications'
    | '/FashionBattle/account/role-casting'
    | '/FashionBattle/account/role-judgements'
    | '/FashionBattle/account/role-ratings'
    | '/FashionBattle/angels/$slug'
    | '/FashionBattle/apply/$contestId'
    | '/FashionBattle/contestant/$contestantId'
    | '/FashionBattle/contestants/$slug'
    | '/FashionBattle/house-of-fashion/$productId'
    | '/FashionBattle/live-contest/$contestId'
    | '/FashionBattle/photography/$photoId'
    | '/brand/$brandSlug'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/FashionBattle/account/'
    | '/FashionBattle/apply/'
    | '/FashionBattle/live-contest/$countryId/$stage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/FashionBattle/about'
    | '/FashionBattle/angels'
    | '/FashionBattle/best-photography'
    | '/FashionBattle/cart'
    | '/FashionBattle/house-of-fashion'
    | '/FashionBattle/live-contest'
    | '/FashionBattle/login'
    | '/FashionBattle/register'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/shop'
    | '/wishlist'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/FashionBattle'
    | '/'
    | '/admin'
    | '/FashionBattle/account/applications'
    | '/FashionBattle/account/notifications'
    | '/FashionBattle/account/profile'
    | '/FashionBattle/account/role-applications'
    | '/FashionBattle/account/role-casting'
    | '/FashionBattle/account/role-judgements'
    | '/FashionBattle/account/role-ratings'
    | '/FashionBattle/angels/$slug'
    | '/FashionBattle/apply/$contestId'
    | '/FashionBattle/contestant/$contestantId'
    | '/FashionBattle/contestants/$slug'
    | '/FashionBattle/house-of-fashion/$productId'
    | '/FashionBattle/live-contest/$contestId'
    | '/FashionBattle/photography/$photoId'
    | '/brand/$brandSlug'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/FashionBattle/account'
    | '/FashionBattle/apply'
    | '/FashionBattle/live-contest/$countryId/$stage'
  id:
    | '__root__'
    | '/_shop'
    | '/sitemap.xml'
    | '/FashionBattle/about'
    | '/FashionBattle/account'
    | '/FashionBattle/angels'
    | '/FashionBattle/apply'
    | '/FashionBattle/best-photography'
    | '/FashionBattle/cart'
    | '/FashionBattle/house-of-fashion'
    | '/FashionBattle/live-contest'
    | '/FashionBattle/login'
    | '/FashionBattle/register'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/categories'
    | '/_shop/checkout'
    | '/_shop/forgot-password'
    | '/_shop/login'
    | '/_shop/orders'
    | '/_shop/register'
    | '/_shop/search'
    | '/_shop/shop'
    | '/_shop/wishlist'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/FashionBattle/'
    | '/_shop/'
    | '/admin/'
    | '/FashionBattle/account/applications'
    | '/FashionBattle/account/notifications'
    | '/FashionBattle/account/profile'
    | '/FashionBattle/account/role-applications'
    | '/FashionBattle/account/role-casting'
    | '/FashionBattle/account/role-judgements'
    | '/FashionBattle/account/role-ratings'
    | '/FashionBattle/angels/$slug'
    | '/FashionBattle/apply/$contestId'
    | '/FashionBattle/contestant/$contestantId'
    | '/FashionBattle/contestants/$slug'
    | '/FashionBattle/house-of-fashion/$productId'
    | '/FashionBattle/live-contest/$contestId'
    | '/FashionBattle/photography/$photoId'
    | '/_shop/brand/$brandSlug'
    | '/_shop/category/$categorySlug'
    | '/_shop/product/$productId'
    | '/FashionBattle/account/'
    | '/FashionBattle/apply/'
    | '/FashionBattle/live-contest/$countryId/$stage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FashionBattleAboutRoute: typeof FashionBattleAboutRoute
  FashionBattleAccountRoute: typeof FashionBattleAccountRouteWithChildren
  FashionBattleAngelsRoute: typeof FashionBattleAngelsRouteWithChildren
  FashionBattleApplyRoute: typeof FashionBattleApplyRouteWithChildren
  FashionBattleBestPhotographyRoute: typeof FashionBattleBestPhotographyRoute
  FashionBattleCartRoute: typeof FashionBattleCartRoute
  FashionBattleHouseOfFashionRoute: typeof FashionBattleHouseOfFashionRouteWithChildren
  FashionBattleLiveContestRoute: typeof FashionBattleLiveContestRouteWithChildren
  FashionBattleLoginRoute: typeof FashionBattleLoginRoute
  FashionBattleRegisterRoute: typeof FashionBattleRegisterRoute
  AdminAbuseReportsRoute: typeof AdminAbuseReportsRoute
  AdminContestantsRoute: typeof AdminContestantsRoute
  AdminLiveContestRoute: typeof AdminLiveContestRoute
  AdminOpenContestRoute: typeof AdminOpenContestRoute
  AdminPhotographersRoute: typeof AdminPhotographersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminTop16Route: typeof AdminTop16Route
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoteControlRoute: typeof AdminVoteControlRoute
  ApiAngelsRoute: typeof ApiAngelsRoute
  ApiCountriesLogosRoute: typeof ApiCountriesLogosRoute
  ApiFlagsRoute: typeof ApiFlagsRoute
  ApiSponsorsRoute: typeof ApiSponsorsRoute
  FashionBattleIndexRoute: typeof FashionBattleIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FashionBattleContestantContestantIdRoute: typeof FashionBattleContestantContestantIdRoute
  FashionBattleContestantsSlugRoute: typeof FashionBattleContestantsSlugRoute
  FashionBattlePhotographyPhotoIdRoute: typeof FashionBattlePhotographyPhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/FashionBattle/': {
      id: '/FashionBattle/'
      path: '/FashionBattle'
      fullPath: '/FashionBattle/'
      preLoaderRoute: typeof FashionBattleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsors': {
      id: '/api/sponsors'
      path: '/api/sponsors'
      fullPath: '/api/sponsors'
      preLoaderRoute: typeof ApiSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flags': {
      id: '/api/flags'
      path: '/api/flags'
      fullPath: '/api/flags'
      preLoaderRoute: typeof ApiFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries-logos': {
      id: '/api/countries-logos'
      path: '/api/countries-logos'
      fullPath: '/api/countries-logos'
      preLoaderRoute: typeof ApiCountriesLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/angels': {
      id: '/api/angels'
      path: '/api/angels'
      fullPath: '/api/angels'
      preLoaderRoute: typeof ApiAngelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vote-control': {
      id: '/admin/vote-control'
      path: '/admin/vote-control'
      fullPath: '/admin/vote-control'
      preLoaderRoute: typeof AdminVoteControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/top-16': {
      id: '/admin/top-16'
      path: '/admin/top-16'
      fullPath: '/admin/top-16'
      preLoaderRoute: typeof AdminTop16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/photographers': {
      id: '/admin/photographers'
      path: '/admin/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof AdminPhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/open-contest': {
      id: '/admin/open-contest'
      path: '/admin/open-contest'
      fullPath: '/admin/open-contest'
      preLoaderRoute: typeof AdminOpenContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-contest': {
      id: '/admin/live-contest'
      path: '/admin/live-contest'
      fullPath: '/admin/live-contest'
      preLoaderRoute: typeof AdminLiveContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contestants': {
      id: '/admin/contestants'
      path: '/admin/contestants'
      fullPath: '/admin/contestants'
      preLoaderRoute: typeof AdminContestantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abuse-reports': {
      id: '/admin/abuse-reports'
      path: '/admin/abuse-reports'
      fullPath: '/admin/abuse-reports'
      preLoaderRoute: typeof AdminAbuseReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/wishlist': {
      id: '/_shop/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/shop': {
      id: '/_shop/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopShopRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/search': {
      id: '/_shop/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/register': {
      id: '/_shop/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof ShopRegisterRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/forgot-password': {
      id: '/_shop/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ShopForgotPasswordRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/categories': {
      id: '/_shop/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof ShopCategoriesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/FashionBattle/register': {
      id: '/FashionBattle/register'
      path: '/FashionBattle/register'
      fullPath: '/FashionBattle/register'
      preLoaderRoute: typeof FashionBattleRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/login': {
      id: '/FashionBattle/login'
      path: '/FashionBattle/login'
      fullPath: '/FashionBattle/login'
      preLoaderRoute: typeof FashionBattleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/live-contest': {
      id: '/FashionBattle/live-contest'
      path: '/FashionBattle/live-contest'
      fullPath: '/FashionBattle/live-contest'
      preLoaderRoute: typeof FashionBattleLiveContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/house-of-fashion': {
      id: '/FashionBattle/house-of-fashion'
      path: '/FashionBattle/house-of-fashion'
      fullPath: '/FashionBattle/house-of-fashion'
      preLoaderRoute: typeof FashionBattleHouseOfFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/cart': {
      id: '/FashionBattle/cart'
      path: '/FashionBattle/cart'
      fullPath: '/FashionBattle/cart'
      preLoaderRoute: typeof FashionBattleCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/best-photography': {
      id: '/FashionBattle/best-photography'
      path: '/FashionBattle/best-photography'
      fullPath: '/FashionBattle/best-photography'
      preLoaderRoute: typeof FashionBattleBestPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/apply': {
      id: '/FashionBattle/apply'
      path: '/FashionBattle/apply'
      fullPath: '/FashionBattle/apply'
      preLoaderRoute: typeof FashionBattleApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/angels': {
      id: '/FashionBattle/angels'
      path: '/FashionBattle/angels'
      fullPath: '/FashionBattle/angels'
      preLoaderRoute: typeof FashionBattleAngelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/account': {
      id: '/FashionBattle/account'
      path: '/FashionBattle/account'
      fullPath: '/FashionBattle/account'
      preLoaderRoute: typeof FashionBattleAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/about': {
      id: '/FashionBattle/about'
      path: '/FashionBattle/about'
      fullPath: '/FashionBattle/about'
      preLoaderRoute: typeof FashionBattleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/apply/': {
      id: '/FashionBattle/apply/'
      path: '/'
      fullPath: '/FashionBattle/apply/'
      preLoaderRoute: typeof FashionBattleApplyIndexRouteImport
      parentRoute: typeof FashionBattleApplyRoute
    }
    '/FashionBattle/account/': {
      id: '/FashionBattle/account/'
      path: '/'
      fullPath: '/FashionBattle/account/'
      preLoaderRoute: typeof FashionBattleAccountIndexRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/_shop/product/$productId': {
      id: '/_shop/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ShopProductProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/category/$categorySlug': {
      id: '/_shop/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof ShopCategoryCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/brand/$brandSlug': {
      id: '/_shop/brand/$brandSlug'
      path: '/brand/$brandSlug'
      fullPath: '/brand/$brandSlug'
      preLoaderRoute: typeof ShopBrandBrandSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/FashionBattle/photography/$photoId': {
      id: '/FashionBattle/photography/$photoId'
      path: '/FashionBattle/photography/$photoId'
      fullPath: '/FashionBattle/photography/$photoId'
      preLoaderRoute: typeof FashionBattlePhotographyPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/live-contest/$contestId': {
      id: '/FashionBattle/live-contest/$contestId'
      path: '/$contestId'
      fullPath: '/FashionBattle/live-contest/$contestId'
      preLoaderRoute: typeof FashionBattleLiveContestContestIdRouteImport
      parentRoute: typeof FashionBattleLiveContestRoute
    }
    '/FashionBattle/house-of-fashion/$productId': {
      id: '/FashionBattle/house-of-fashion/$productId'
      path: '/$productId'
      fullPath: '/FashionBattle/house-of-fashion/$productId'
      preLoaderRoute: typeof FashionBattleHouseOfFashionProductIdRouteImport
      parentRoute: typeof FashionBattleHouseOfFashionRoute
    }
    '/FashionBattle/contestants/$slug': {
      id: '/FashionBattle/contestants/$slug'
      path: '/FashionBattle/contestants/$slug'
      fullPath: '/FashionBattle/contestants/$slug'
      preLoaderRoute: typeof FashionBattleContestantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/contestant/$contestantId': {
      id: '/FashionBattle/contestant/$contestantId'
      path: '/FashionBattle/contestant/$contestantId'
      fullPath: '/FashionBattle/contestant/$contestantId'
      preLoaderRoute: typeof FashionBattleContestantContestantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FashionBattle/apply/$contestId': {
      id: '/FashionBattle/apply/$contestId'
      path: '/$contestId'
      fullPath: '/FashionBattle/apply/$contestId'
      preLoaderRoute: typeof FashionBattleApplyContestIdRouteImport
      parentRoute: typeof FashionBattleApplyRoute
    }
    '/FashionBattle/angels/$slug': {
      id: '/FashionBattle/angels/$slug'
      path: '/$slug'
      fullPath: '/FashionBattle/angels/$slug'
      preLoaderRoute: typeof FashionBattleAngelsSlugRouteImport
      parentRoute: typeof FashionBattleAngelsRoute
    }
    '/FashionBattle/account/role-ratings': {
      id: '/FashionBattle/account/role-ratings'
      path: '/role-ratings'
      fullPath: '/FashionBattle/account/role-ratings'
      preLoaderRoute: typeof FashionBattleAccountRoleRatingsRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/role-judgements': {
      id: '/FashionBattle/account/role-judgements'
      path: '/role-judgements'
      fullPath: '/FashionBattle/account/role-judgements'
      preLoaderRoute: typeof FashionBattleAccountRoleJudgementsRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/role-casting': {
      id: '/FashionBattle/account/role-casting'
      path: '/role-casting'
      fullPath: '/FashionBattle/account/role-casting'
      preLoaderRoute: typeof FashionBattleAccountRoleCastingRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/role-applications': {
      id: '/FashionBattle/account/role-applications'
      path: '/role-applications'
      fullPath: '/FashionBattle/account/role-applications'
      preLoaderRoute: typeof FashionBattleAccountRoleApplicationsRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/profile': {
      id: '/FashionBattle/account/profile'
      path: '/profile'
      fullPath: '/FashionBattle/account/profile'
      preLoaderRoute: typeof FashionBattleAccountProfileRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/notifications': {
      id: '/FashionBattle/account/notifications'
      path: '/notifications'
      fullPath: '/FashionBattle/account/notifications'
      preLoaderRoute: typeof FashionBattleAccountNotificationsRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/account/applications': {
      id: '/FashionBattle/account/applications'
      path: '/applications'
      fullPath: '/FashionBattle/account/applications'
      preLoaderRoute: typeof FashionBattleAccountApplicationsRouteImport
      parentRoute: typeof FashionBattleAccountRoute
    }
    '/FashionBattle/live-contest/$countryId/$stage': {
      id: '/FashionBattle/live-contest/$countryId/$stage'
      path: '/$countryId/$stage'
      fullPath: '/FashionBattle/live-contest/$countryId/$stage'
      preLoaderRoute: typeof FashionBattleLiveContestCountryIdStageRouteImport
      parentRoute: typeof FashionBattleLiveContestRoute
    }
  }
}

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCategoriesRoute: typeof ShopCategoriesRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopForgotPasswordRoute: typeof ShopForgotPasswordRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopRegisterRoute: typeof ShopRegisterRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopShopRoute: typeof ShopShopRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopBrandBrandSlugRoute: typeof ShopBrandBrandSlugRoute
  ShopCategoryCategorySlugRoute: typeof ShopCategoryCategorySlugRoute
  ShopProductProductIdRoute: typeof ShopProductProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCategoriesRoute: ShopCategoriesRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopForgotPasswordRoute: ShopForgotPasswordRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopRegisterRoute: ShopRegisterRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopShopRoute: ShopShopRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopBrandBrandSlugRoute: ShopBrandBrandSlugRoute,
  ShopCategoryCategorySlugRoute: ShopCategoryCategorySlugRoute,
  ShopProductProductIdRoute: ShopProductProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface FashionBattleAccountRouteChildren {
  FashionBattleAccountApplicationsRoute: typeof FashionBattleAccountApplicationsRoute
  FashionBattleAccountNotificationsRoute: typeof FashionBattleAccountNotificationsRoute
  FashionBattleAccountProfileRoute: typeof FashionBattleAccountProfileRoute
  FashionBattleAccountRoleApplicationsRoute: typeof FashionBattleAccountRoleApplicationsRoute
  FashionBattleAccountRoleCastingRoute: typeof FashionBattleAccountRoleCastingRoute
  FashionBattleAccountRoleJudgementsRoute: typeof FashionBattleAccountRoleJudgementsRoute
  FashionBattleAccountRoleRatingsRoute: typeof FashionBattleAccountRoleRatingsRoute
  FashionBattleAccountIndexRoute: typeof FashionBattleAccountIndexRoute
}

const FashionBattleAccountRouteChildren: FashionBattleAccountRouteChildren = {
  FashionBattleAccountApplicationsRoute: FashionBattleAccountApplicationsRoute,
  FashionBattleAccountNotificationsRoute:
    FashionBattleAccountNotificationsRoute,
  FashionBattleAccountProfileRoute: FashionBattleAccountProfileRoute,
  FashionBattleAccountRoleApplicationsRoute:
    FashionBattleAccountRoleApplicationsRoute,
  FashionBattleAccountRoleCastingRoute: FashionBattleAccountRoleCastingRoute,
  FashionBattleAccountRoleJudgementsRoute:
    FashionBattleAccountRoleJudgementsRoute,
  FashionBattleAccountRoleRatingsRoute: FashionBattleAccountRoleRatingsRoute,
  FashionBattleAccountIndexRoute: FashionBattleAccountIndexRoute,
}

const FashionBattleAccountRouteWithChildren =
  FashionBattleAccountRoute._addFileChildren(FashionBattleAccountRouteChildren)

interface FashionBattleAngelsRouteChildren {
  FashionBattleAngelsSlugRoute: typeof FashionBattleAngelsSlugRoute
}

const FashionBattleAngelsRouteChildren: FashionBattleAngelsRouteChildren = {
  FashionBattleAngelsSlugRoute: FashionBattleAngelsSlugRoute,
}

const FashionBattleAngelsRouteWithChildren =
  FashionBattleAngelsRoute._addFileChildren(FashionBattleAngelsRouteChildren)

interface FashionBattleApplyRouteChildren {
  FashionBattleApplyContestIdRoute: typeof FashionBattleApplyContestIdRoute
  FashionBattleApplyIndexRoute: typeof FashionBattleApplyIndexRoute
}

const FashionBattleApplyRouteChildren: FashionBattleApplyRouteChildren = {
  FashionBattleApplyContestIdRoute: FashionBattleApplyContestIdRoute,
  FashionBattleApplyIndexRoute: FashionBattleApplyIndexRoute,
}

const FashionBattleApplyRouteWithChildren =
  FashionBattleApplyRoute._addFileChildren(FashionBattleApplyRouteChildren)

interface FashionBattleHouseOfFashionRouteChildren {
  FashionBattleHouseOfFashionProductIdRoute: typeof FashionBattleHouseOfFashionProductIdRoute
}

const FashionBattleHouseOfFashionRouteChildren: FashionBattleHouseOfFashionRouteChildren =
  {
    FashionBattleHouseOfFashionProductIdRoute:
      FashionBattleHouseOfFashionProductIdRoute,
  }

const FashionBattleHouseOfFashionRouteWithChildren =
  FashionBattleHouseOfFashionRoute._addFileChildren(
    FashionBattleHouseOfFashionRouteChildren,
  )

interface FashionBattleLiveContestRouteChildren {
  FashionBattleLiveContestContestIdRoute: typeof FashionBattleLiveContestContestIdRoute
  FashionBattleLiveContestCountryIdStageRoute: typeof FashionBattleLiveContestCountryIdStageRoute
}

const FashionBattleLiveContestRouteChildren: FashionBattleLiveContestRouteChildren =
  {
    FashionBattleLiveContestContestIdRoute:
      FashionBattleLiveContestContestIdRoute,
    FashionBattleLiveContestCountryIdStageRoute:
      FashionBattleLiveContestCountryIdStageRoute,
  }

const FashionBattleLiveContestRouteWithChildren =
  FashionBattleLiveContestRoute._addFileChildren(
    FashionBattleLiveContestRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FashionBattleAboutRoute: FashionBattleAboutRoute,
  FashionBattleAccountRoute: FashionBattleAccountRouteWithChildren,
  FashionBattleAngelsRoute: FashionBattleAngelsRouteWithChildren,
  FashionBattleApplyRoute: FashionBattleApplyRouteWithChildren,
  FashionBattleBestPhotographyRoute: FashionBattleBestPhotographyRoute,
  FashionBattleCartRoute: FashionBattleCartRoute,
  FashionBattleHouseOfFashionRoute:
    FashionBattleHouseOfFashionRouteWithChildren,
  FashionBattleLiveContestRoute: FashionBattleLiveContestRouteWithChildren,
  FashionBattleLoginRoute: FashionBattleLoginRoute,
  FashionBattleRegisterRoute: FashionBattleRegisterRoute,
  AdminAbuseReportsRoute: AdminAbuseReportsRoute,
  AdminContestantsRoute: AdminContestantsRoute,
  AdminLiveContestRoute: AdminLiveContestRoute,
  AdminOpenContestRoute: AdminOpenContestRoute,
  AdminPhotographersRoute: AdminPhotographersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminTop16Route: AdminTop16Route,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoteControlRoute: AdminVoteControlRoute,
  ApiAngelsRoute: ApiAngelsRoute,
  ApiCountriesLogosRoute: ApiCountriesLogosRoute,
  ApiFlagsRoute: ApiFlagsRoute,
  ApiSponsorsRoute: ApiSponsorsRoute,
  FashionBattleIndexRoute: FashionBattleIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  FashionBattleContestantContestantIdRoute:
    FashionBattleContestantContestantIdRoute,
  FashionBattleContestantsSlugRoute: FashionBattleContestantsSlugRoute,
  FashionBattlePhotographyPhotoIdRoute: FashionBattlePhotographyPhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
