/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveContestRouteImport } from './routes/live-contest'
import { Route as HouseOfFashionRouteImport } from './routes/house-of-fashion'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BestPhotographyRouteImport } from './routes/best-photography'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AngelsRouteImport } from './routes/angels'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopRegisterRouteImport } from './routes/shop.register'
import { Route as ShopLoginRouteImport } from './routes/shop.login'
import { Route as ShopCategoriesRouteImport } from './routes/shop.categories'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as PhotographyPhotoIdRouteImport } from './routes/photography.$photoId'
import { Route as LiveContestContestIdRouteImport } from './routes/live-contest.$contestId'
import { Route as HouseOfFashionProductIdRouteImport } from './routes/house-of-fashion.$productId'
import { Route as ContestantsSlugRouteImport } from './routes/contestants.$slug'
import { Route as ContestantContestantIdRouteImport } from './routes/contestant.$contestantId'
import { Route as ApplyContestIdRouteImport } from './routes/apply.$contestId'
import { Route as ApiSponsorsRouteImport } from './routes/api.sponsors'
import { Route as ApiFlagsRouteImport } from './routes/api.flags'
import { Route as ApiCountriesLogosRouteImport } from './routes/api.countries-logos'
import { Route as ApiAngelsRouteImport } from './routes/api.angels'
import { Route as AngelsSlugRouteImport } from './routes/angels.$slug'
import { Route as AdminVoteControlRouteImport } from './routes/admin.vote-control'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTop16RouteImport } from './routes/admin.top-16'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPhotographersRouteImport } from './routes/admin.photographers'
import { Route as AdminOpenContestRouteImport } from './routes/admin.open-contest'
import { Route as AdminLiveContestRouteImport } from './routes/admin.live-contest'
import { Route as AdminContestantsRouteImport } from './routes/admin.contestants'
import { Route as AdminAbuseReportsRouteImport } from './routes/admin.abuse-reports'
import { Route as AccountRoleRatingsRouteImport } from './routes/account.role-ratings'
import { Route as AccountRoleJudgementsRouteImport } from './routes/account.role-judgements'
import { Route as AccountRoleCastingRouteImport } from './routes/account.role-casting'
import { Route as AccountRoleApplicationsRouteImport } from './routes/account.role-applications'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountApplicationsRouteImport } from './routes/account.applications'
import { Route as ShopProductProductIdRouteImport } from './routes/shop.product.$productId'
import { Route as LiveContestCountryIdStageRouteImport } from './routes/live-contest.$countryId.$stage'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveContestRoute = LiveContestRouteImport.update({
  id: '/live-contest',
  path: '/live-contest',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseOfFashionRoute = HouseOfFashionRouteImport.update({
  id: '/house-of-fashion',
  path: '/house-of-fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPhotographyRoute = BestPhotographyRouteImport.update({
  id: '/best-photography',
  path: '/best-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AngelsRoute = AngelsRouteImport.update({
  id: '/angels',
  path: '/angels',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopRegisterRoute = ShopRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoriesRoute = ShopCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const PhotographyPhotoIdRoute = PhotographyPhotoIdRouteImport.update({
  id: '/photography/$photoId',
  path: '/photography/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveContestContestIdRoute = LiveContestContestIdRouteImport.update({
  id: '/$contestId',
  path: '/$contestId',
  getParentRoute: () => LiveContestRoute,
} as any)
const HouseOfFashionProductIdRoute = HouseOfFashionProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => HouseOfFashionRoute,
} as any)
const ContestantsSlugRoute = ContestantsSlugRouteImport.update({
  id: '/contestants/$slug',
  path: '/contestants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantContestantIdRoute = ContestantContestantIdRouteImport.update({
  id: '/contestant/$contestantId',
  path: '/contestant/$contestantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyContestIdRoute = ApplyContestIdRouteImport.update({
  id: '/$contestId',
  path: '/$contestId',
  getParentRoute: () => ApplyRoute,
} as any)
const ApiSponsorsRoute = ApiSponsorsRouteImport.update({
  id: '/api/sponsors',
  path: '/api/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagsRoute = ApiFlagsRouteImport.update({
  id: '/api/flags',
  path: '/api/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesLogosRoute = ApiCountriesLogosRouteImport.update({
  id: '/api/countries-logos',
  path: '/api/countries-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAngelsRoute = ApiAngelsRouteImport.update({
  id: '/api/angels',
  path: '/api/angels',
  getParentRoute: () => rootRouteImport,
} as any)
const AngelsSlugRoute = AngelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AngelsRoute,
} as any)
const AdminVoteControlRoute = AdminVoteControlRouteImport.update({
  id: '/admin/vote-control',
  path: '/admin/vote-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTop16Route = AdminTop16RouteImport.update({
  id: '/admin/top-16',
  path: '/admin/top-16',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotographersRoute = AdminPhotographersRouteImport.update({
  id: '/admin/photographers',
  path: '/admin/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpenContestRoute = AdminOpenContestRouteImport.update({
  id: '/admin/open-contest',
  path: '/admin/open-contest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveContestRoute = AdminLiveContestRouteImport.update({
  id: '/admin/live-contest',
  path: '/admin/live-contest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestantsRoute = AdminContestantsRouteImport.update({
  id: '/admin/contestants',
  path: '/admin/contestants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbuseReportsRoute = AdminAbuseReportsRouteImport.update({
  id: '/admin/abuse-reports',
  path: '/admin/abuse-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoleRatingsRoute = AccountRoleRatingsRouteImport.update({
  id: '/role-ratings',
  path: '/role-ratings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRoleJudgementsRoute = AccountRoleJudgementsRouteImport.update({
  id: '/role-judgements',
  path: '/role-judgements',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRoleCastingRoute = AccountRoleCastingRouteImport.update({
  id: '/role-casting',
  path: '/role-casting',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRoleApplicationsRoute = AccountRoleApplicationsRouteImport.update({
  id: '/role-applications',
  path: '/role-applications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AccountRoute,
} as any)
const ShopProductProductIdRoute = ShopProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const LiveContestCountryIdStageRoute =
  LiveContestCountryIdStageRouteImport.update({
    id: '/$countryId/$stage',
    path: '/$countryId/$stage',
    getParentRoute: () => LiveContestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/angels': typeof AngelsRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/best-photography': typeof BestPhotographyRoute
  '/cart': typeof CartRoute
  '/house-of-fashion': typeof HouseOfFashionRouteWithChildren
  '/live-contest': typeof LiveContestRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/role-applications': typeof AccountRoleApplicationsRoute
  '/account/role-casting': typeof AccountRoleCastingRoute
  '/account/role-judgements': typeof AccountRoleJudgementsRoute
  '/account/role-ratings': typeof AccountRoleRatingsRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/angels/$slug': typeof AngelsSlugRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/apply/$contestId': typeof ApplyContestIdRoute
  '/contestant/$contestantId': typeof ContestantContestantIdRoute
  '/contestants/$slug': typeof ContestantsSlugRoute
  '/house-of-fashion/$productId': typeof HouseOfFashionProductIdRoute
  '/live-contest/$contestId': typeof LiveContestContestIdRoute
  '/photography/$photoId': typeof PhotographyPhotoIdRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/register': typeof ShopRegisterRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/live-contest/$countryId/$stage': typeof LiveContestCountryIdStageRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/angels': typeof AngelsRouteWithChildren
  '/best-photography': typeof BestPhotographyRoute
  '/cart': typeof CartRoute
  '/house-of-fashion': typeof HouseOfFashionRouteWithChildren
  '/live-contest': typeof LiveContestRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/role-applications': typeof AccountRoleApplicationsRoute
  '/account/role-casting': typeof AccountRoleCastingRoute
  '/account/role-judgements': typeof AccountRoleJudgementsRoute
  '/account/role-ratings': typeof AccountRoleRatingsRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/angels/$slug': typeof AngelsSlugRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/apply/$contestId': typeof ApplyContestIdRoute
  '/contestant/$contestantId': typeof ContestantContestantIdRoute
  '/contestants/$slug': typeof ContestantsSlugRoute
  '/house-of-fashion/$productId': typeof HouseOfFashionProductIdRoute
  '/live-contest/$contestId': typeof LiveContestContestIdRoute
  '/photography/$photoId': typeof PhotographyPhotoIdRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/register': typeof ShopRegisterRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/shop': typeof ShopIndexRoute
  '/live-contest/$countryId/$stage': typeof LiveContestCountryIdStageRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/angels': typeof AngelsRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/best-photography': typeof BestPhotographyRoute
  '/cart': typeof CartRoute
  '/house-of-fashion': typeof HouseOfFashionRouteWithChildren
  '/live-contest': typeof LiveContestRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/role-applications': typeof AccountRoleApplicationsRoute
  '/account/role-casting': typeof AccountRoleCastingRoute
  '/account/role-judgements': typeof AccountRoleJudgementsRoute
  '/account/role-ratings': typeof AccountRoleRatingsRoute
  '/admin/abuse-reports': typeof AdminAbuseReportsRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/live-contest': typeof AdminLiveContestRoute
  '/admin/open-contest': typeof AdminOpenContestRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/top-16': typeof AdminTop16Route
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-control': typeof AdminVoteControlRoute
  '/angels/$slug': typeof AngelsSlugRoute
  '/api/angels': typeof ApiAngelsRoute
  '/api/countries-logos': typeof ApiCountriesLogosRoute
  '/api/flags': typeof ApiFlagsRoute
  '/api/sponsors': typeof ApiSponsorsRoute
  '/apply/$contestId': typeof ApplyContestIdRoute
  '/contestant/$contestantId': typeof ContestantContestantIdRoute
  '/contestants/$slug': typeof ContestantsSlugRoute
  '/house-of-fashion/$productId': typeof HouseOfFashionProductIdRoute
  '/live-contest/$contestId': typeof LiveContestContestIdRoute
  '/photography/$photoId': typeof PhotographyPhotoIdRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/register': typeof ShopRegisterRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/live-contest/$countryId/$stage': typeof LiveContestCountryIdStageRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/angels'
    | '/apply'
    | '/best-photography'
    | '/cart'
    | '/house-of-fashion'
    | '/live-contest'
    | '/login'
    | '/register'
    | '/shop'
    | '/sitemap.xml'
    | '/account/applications'
    | '/account/notifications'
    | '/account/profile'
    | '/account/role-applications'
    | '/account/role-casting'
    | '/account/role-judgements'
    | '/account/role-ratings'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/angels/$slug'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/apply/$contestId'
    | '/contestant/$contestantId'
    | '/contestants/$slug'
    | '/house-of-fashion/$productId'
    | '/live-contest/$contestId'
    | '/photography/$photoId'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/login'
    | '/shop/register'
    | '/account/'
    | '/admin/'
    | '/apply/'
    | '/shop/'
    | '/live-contest/$countryId/$stage'
    | '/shop/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/angels'
    | '/best-photography'
    | '/cart'
    | '/house-of-fashion'
    | '/live-contest'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/account/applications'
    | '/account/notifications'
    | '/account/profile'
    | '/account/role-applications'
    | '/account/role-casting'
    | '/account/role-judgements'
    | '/account/role-ratings'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/angels/$slug'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/apply/$contestId'
    | '/contestant/$contestantId'
    | '/contestants/$slug'
    | '/house-of-fashion/$productId'
    | '/live-contest/$contestId'
    | '/photography/$photoId'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/login'
    | '/shop/register'
    | '/account'
    | '/admin'
    | '/apply'
    | '/shop'
    | '/live-contest/$countryId/$stage'
    | '/shop/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/angels'
    | '/apply'
    | '/best-photography'
    | '/cart'
    | '/house-of-fashion'
    | '/live-contest'
    | '/login'
    | '/register'
    | '/shop'
    | '/sitemap.xml'
    | '/account/applications'
    | '/account/notifications'
    | '/account/profile'
    | '/account/role-applications'
    | '/account/role-casting'
    | '/account/role-judgements'
    | '/account/role-ratings'
    | '/admin/abuse-reports'
    | '/admin/contestants'
    | '/admin/live-contest'
    | '/admin/open-contest'
    | '/admin/photographers'
    | '/admin/reports'
    | '/admin/sponsors'
    | '/admin/top-16'
    | '/admin/users'
    | '/admin/vote-control'
    | '/angels/$slug'
    | '/api/angels'
    | '/api/countries-logos'
    | '/api/flags'
    | '/api/sponsors'
    | '/apply/$contestId'
    | '/contestant/$contestantId'
    | '/contestants/$slug'
    | '/house-of-fashion/$productId'
    | '/live-contest/$contestId'
    | '/photography/$photoId'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/login'
    | '/shop/register'
    | '/account/'
    | '/admin/'
    | '/apply/'
    | '/shop/'
    | '/live-contest/$countryId/$stage'
    | '/shop/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AngelsRoute: typeof AngelsRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  BestPhotographyRoute: typeof BestPhotographyRoute
  CartRoute: typeof CartRoute
  HouseOfFashionRoute: typeof HouseOfFashionRouteWithChildren
  LiveContestRoute: typeof LiveContestRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAbuseReportsRoute: typeof AdminAbuseReportsRoute
  AdminContestantsRoute: typeof AdminContestantsRoute
  AdminLiveContestRoute: typeof AdminLiveContestRoute
  AdminOpenContestRoute: typeof AdminOpenContestRoute
  AdminPhotographersRoute: typeof AdminPhotographersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminTop16Route: typeof AdminTop16Route
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoteControlRoute: typeof AdminVoteControlRoute
  ApiAngelsRoute: typeof ApiAngelsRoute
  ApiCountriesLogosRoute: typeof ApiCountriesLogosRoute
  ApiFlagsRoute: typeof ApiFlagsRoute
  ApiSponsorsRoute: typeof ApiSponsorsRoute
  ContestantContestantIdRoute: typeof ContestantContestantIdRoute
  ContestantsSlugRoute: typeof ContestantsSlugRoute
  PhotographyPhotoIdRoute: typeof PhotographyPhotoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-contest': {
      id: '/live-contest'
      path: '/live-contest'
      fullPath: '/live-contest'
      preLoaderRoute: typeof LiveContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-of-fashion': {
      id: '/house-of-fashion'
      path: '/house-of-fashion'
      fullPath: '/house-of-fashion'
      preLoaderRoute: typeof HouseOfFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-photography': {
      id: '/best-photography'
      path: '/best-photography'
      fullPath: '/best-photography'
      preLoaderRoute: typeof BestPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angels': {
      id: '/angels'
      path: '/angels'
      fullPath: '/angels'
      preLoaderRoute: typeof AngelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/register': {
      id: '/shop/register'
      path: '/register'
      fullPath: '/shop/register'
      preLoaderRoute: typeof ShopRegisterRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/login': {
      id: '/shop/login'
      path: '/login'
      fullPath: '/shop/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/categories': {
      id: '/shop/categories'
      path: '/categories'
      fullPath: '/shop/categories'
      preLoaderRoute: typeof ShopCategoriesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/photography/$photoId': {
      id: '/photography/$photoId'
      path: '/photography/$photoId'
      fullPath: '/photography/$photoId'
      preLoaderRoute: typeof PhotographyPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-contest/$contestId': {
      id: '/live-contest/$contestId'
      path: '/$contestId'
      fullPath: '/live-contest/$contestId'
      preLoaderRoute: typeof LiveContestContestIdRouteImport
      parentRoute: typeof LiveContestRoute
    }
    '/house-of-fashion/$productId': {
      id: '/house-of-fashion/$productId'
      path: '/$productId'
      fullPath: '/house-of-fashion/$productId'
      preLoaderRoute: typeof HouseOfFashionProductIdRouteImport
      parentRoute: typeof HouseOfFashionRoute
    }
    '/contestants/$slug': {
      id: '/contestants/$slug'
      path: '/contestants/$slug'
      fullPath: '/contestants/$slug'
      preLoaderRoute: typeof ContestantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestant/$contestantId': {
      id: '/contestant/$contestantId'
      path: '/contestant/$contestantId'
      fullPath: '/contestant/$contestantId'
      preLoaderRoute: typeof ContestantContestantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$contestId': {
      id: '/apply/$contestId'
      path: '/$contestId'
      fullPath: '/apply/$contestId'
      preLoaderRoute: typeof ApplyContestIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/api/sponsors': {
      id: '/api/sponsors'
      path: '/api/sponsors'
      fullPath: '/api/sponsors'
      preLoaderRoute: typeof ApiSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flags': {
      id: '/api/flags'
      path: '/api/flags'
      fullPath: '/api/flags'
      preLoaderRoute: typeof ApiFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries-logos': {
      id: '/api/countries-logos'
      path: '/api/countries-logos'
      fullPath: '/api/countries-logos'
      preLoaderRoute: typeof ApiCountriesLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/angels': {
      id: '/api/angels'
      path: '/api/angels'
      fullPath: '/api/angels'
      preLoaderRoute: typeof ApiAngelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angels/$slug': {
      id: '/angels/$slug'
      path: '/$slug'
      fullPath: '/angels/$slug'
      preLoaderRoute: typeof AngelsSlugRouteImport
      parentRoute: typeof AngelsRoute
    }
    '/admin/vote-control': {
      id: '/admin/vote-control'
      path: '/admin/vote-control'
      fullPath: '/admin/vote-control'
      preLoaderRoute: typeof AdminVoteControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/top-16': {
      id: '/admin/top-16'
      path: '/admin/top-16'
      fullPath: '/admin/top-16'
      preLoaderRoute: typeof AdminTop16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/photographers': {
      id: '/admin/photographers'
      path: '/admin/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof AdminPhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/open-contest': {
      id: '/admin/open-contest'
      path: '/admin/open-contest'
      fullPath: '/admin/open-contest'
      preLoaderRoute: typeof AdminOpenContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-contest': {
      id: '/admin/live-contest'
      path: '/admin/live-contest'
      fullPath: '/admin/live-contest'
      preLoaderRoute: typeof AdminLiveContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contestants': {
      id: '/admin/contestants'
      path: '/admin/contestants'
      fullPath: '/admin/contestants'
      preLoaderRoute: typeof AdminContestantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abuse-reports': {
      id: '/admin/abuse-reports'
      path: '/admin/abuse-reports'
      fullPath: '/admin/abuse-reports'
      preLoaderRoute: typeof AdminAbuseReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/role-ratings': {
      id: '/account/role-ratings'
      path: '/role-ratings'
      fullPath: '/account/role-ratings'
      preLoaderRoute: typeof AccountRoleRatingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/role-judgements': {
      id: '/account/role-judgements'
      path: '/role-judgements'
      fullPath: '/account/role-judgements'
      preLoaderRoute: typeof AccountRoleJudgementsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/role-casting': {
      id: '/account/role-casting'
      path: '/role-casting'
      fullPath: '/account/role-casting'
      preLoaderRoute: typeof AccountRoleCastingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/role-applications': {
      id: '/account/role-applications'
      path: '/role-applications'
      fullPath: '/account/role-applications'
      preLoaderRoute: typeof AccountRoleApplicationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/applications': {
      id: '/account/applications'
      path: '/applications'
      fullPath: '/account/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/product/$productId': {
      id: '/shop/product/$productId'
      path: '/product/$productId'
      fullPath: '/shop/product/$productId'
      preLoaderRoute: typeof ShopProductProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/live-contest/$countryId/$stage': {
      id: '/live-contest/$countryId/$stage'
      path: '/$countryId/$stage'
      fullPath: '/live-contest/$countryId/$stage'
      preLoaderRoute: typeof LiveContestCountryIdStageRouteImport
      parentRoute: typeof LiveContestRoute
    }
  }
}

interface AccountRouteChildren {
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRoleApplicationsRoute: typeof AccountRoleApplicationsRoute
  AccountRoleCastingRoute: typeof AccountRoleCastingRoute
  AccountRoleJudgementsRoute: typeof AccountRoleJudgementsRoute
  AccountRoleRatingsRoute: typeof AccountRoleRatingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRoleApplicationsRoute: AccountRoleApplicationsRoute,
  AccountRoleCastingRoute: AccountRoleCastingRoute,
  AccountRoleJudgementsRoute: AccountRoleJudgementsRoute,
  AccountRoleRatingsRoute: AccountRoleRatingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AngelsRouteChildren {
  AngelsSlugRoute: typeof AngelsSlugRoute
}

const AngelsRouteChildren: AngelsRouteChildren = {
  AngelsSlugRoute: AngelsSlugRoute,
}

const AngelsRouteWithChildren =
  AngelsRoute._addFileChildren(AngelsRouteChildren)

interface ApplyRouteChildren {
  ApplyContestIdRoute: typeof ApplyContestIdRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyContestIdRoute: ApplyContestIdRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface HouseOfFashionRouteChildren {
  HouseOfFashionProductIdRoute: typeof HouseOfFashionProductIdRoute
}

const HouseOfFashionRouteChildren: HouseOfFashionRouteChildren = {
  HouseOfFashionProductIdRoute: HouseOfFashionProductIdRoute,
}

const HouseOfFashionRouteWithChildren = HouseOfFashionRoute._addFileChildren(
  HouseOfFashionRouteChildren,
)

interface LiveContestRouteChildren {
  LiveContestContestIdRoute: typeof LiveContestContestIdRoute
  LiveContestCountryIdStageRoute: typeof LiveContestCountryIdStageRoute
}

const LiveContestRouteChildren: LiveContestRouteChildren = {
  LiveContestContestIdRoute: LiveContestContestIdRoute,
  LiveContestCountryIdStageRoute: LiveContestCountryIdStageRoute,
}

const LiveContestRouteWithChildren = LiveContestRoute._addFileChildren(
  LiveContestRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCategoriesRoute: typeof ShopCategoriesRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopRegisterRoute: typeof ShopRegisterRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductProductIdRoute: typeof ShopProductProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCategoriesRoute: ShopCategoriesRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopRegisterRoute: ShopRegisterRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductProductIdRoute: ShopProductProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AngelsRoute: AngelsRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  BestPhotographyRoute: BestPhotographyRoute,
  CartRoute: CartRoute,
  HouseOfFashionRoute: HouseOfFashionRouteWithChildren,
  LiveContestRoute: LiveContestRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAbuseReportsRoute: AdminAbuseReportsRoute,
  AdminContestantsRoute: AdminContestantsRoute,
  AdminLiveContestRoute: AdminLiveContestRoute,
  AdminOpenContestRoute: AdminOpenContestRoute,
  AdminPhotographersRoute: AdminPhotographersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminTop16Route: AdminTop16Route,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoteControlRoute: AdminVoteControlRoute,
  ApiAngelsRoute: ApiAngelsRoute,
  ApiCountriesLogosRoute: ApiCountriesLogosRoute,
  ApiFlagsRoute: ApiFlagsRoute,
  ApiSponsorsRoute: ApiSponsorsRoute,
  ContestantContestantIdRoute: ContestantContestantIdRoute,
  ContestantsSlugRoute: ContestantsSlugRoute,
  PhotographyPhotoIdRoute: PhotographyPhotoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
